export const GENERATE_SCAN_QRCODE = 'GENERATE_SCAN_QRCODE'
export const DATA_INIT = 'DATA_INIT'

export const TOGGLE_SCAN_HELP_INFORMATION = 'TOGGLE_SCAN_HELP_INFORMATION'
export const HIDE_SCAN_HELP_INFORMATION = 'HIDE_SCAN_HELP_INFORMATION'

export const READY_IMPORT_DIARIES = 'READY_IMPORT_DIARIES'
export const CANCEL_IMPORT_DIARIES = 'CANCEL_IMPORT_DIARIES'
export const OPEN_LIST_SINGLE_VIEW = 'OPEN_LIST_SINGLE_VIEW'
export const CLOSE_LIST_SINGLE_VIEW = 'CLOSE_LIST_SINGLE_VIEW'
export const CHANGE_CURRENT_GRID = 'CHANGE_CURRENT_GRID'

export const UPDATE_GRID_CONTENT = 'UPDATE_GRID_CONTENT'

export const GENERATE_IMPORT_SCAN_QRCODE = 'GENERATE_IMPORT_SCAN_QRCODE'
export const UPDATE_SERVER_DATA = 'UPDATE_SERVER_DATA'
